### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by johntdyer** [mogorman/pam_gmail#1]
Hello,

 This looks really interesting, but I was hoping you may have some tips for using it on CentOS 6?

*\*   I am I have compiled it 

``` bash
 gcc -fPIC -DPIC -shared -rdynamic -o pam_gmail.so  pam_gmail.c
```

*\* then copied to /lib64/security 

*\* then added to /etc/pam.d/login

``` bash
auth       requisite         pam_gmail.so debug
```

but no dice... I am not sure really how to proceed from here... any help would be great

**Comment by mogorman** [comment]
sorry im so slow to get back to you .  by no dice do you mean pam throws up and says unallowed?  where exactly s the problem?
